CREATE TABLE IF NOT EXISTS `user` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(128),
  `password` BIGINT(20) ,
  `count` BIGINT(100) DEFAULT 0,
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;